import { Request, Response } from 'express';
import jwt from 'jsonwebtoken';
import { prisma } from '../index';

// In-memory store for OTPs (For production, consider Redis or a DB table)
const otpStore = new Map<string, { otp: string, expiresAt: number }>();

export const requestOtp = async (req: Request, res: Response) => {
  const { phone } = req.body;

  if (!phone || !phone.match(/^(?:\+9665|05)\d{8}$/)) {
    return res.status(400).json({
      success: false,
      error: {
        code: 'VALIDATION_ERROR',
        message: 'Phone number is invalid',
        fields: { phone: 'Must be a valid Saudi mobile number (+9665XXXXXXXX or 05XXXXXXXX)' }
      }
    });
  }

  // Generate a 6-digit OTP
  const generatedOtp = Math.floor(100000 + Math.random() * 900000).toString();
  
  // Set expiration (5 minutes)
  const expiresAt = Date.now() + 5 * 60 * 1000;
  
  otpStore.set(phone, { otp: generatedOtp, expiresAt });

  // In a real app, you would integrate an SMS provider (e.g., Twilio, Unifonic) here
  console.log(`[Dev Only] Generated OTP for ${phone}: ${generatedOtp}`);

  res.json({
    success: true,
    data: {
      phone: phone,
      expires_in: 300,
      resend_after: 30
    }
  });
};

export const verifyOtp = async (req: Request, res: Response) => {
  const { phone, otp } = req.body;

  if (!phone || !otp || otp.length !== 6) {
    return res.status(400).json({
      success: false,
      error: { code: 'VALIDATION_ERROR', message: 'Invalid phone or OTP format' }
    });
  }

  const storedData = otpStore.get(phone);

  if (!storedData) {
    return res.status(400).json({ success: false, error: { code: 'INVALID_OTP', message: 'OTP not found or expired' } });
  }

  if (Date.now() > storedData.expiresAt) {
    otpStore.delete(phone);
    return res.status(400).json({ success: false, error: { code: 'OTP_EXPIRED', message: 'OTP has expired' } });
  }

  if (storedData.otp !== otp) {
    return res.status(400).json({ success: false, error: { code: 'INVALID_OTP', message: 'Incorrect OTP' } });
  }

  // OTP is valid. Clear it.
  otpStore.delete(phone);

  try {
    // Check if driver exists, if not, create a basic record (or reject depending on business rules)
    // For this implementation, we assume any verified phone belongs to a Driver if they login via this app.
    // Realistically you'd want to check if they are a User or Driver. We'll check Driver first.
    let driver = await prisma.driver.findUnique({ where: { phone_primary: phone } });
    
    if (!driver) {
      // Auto-create a temporary driver profile for demonstration. 
      // In production, an admin might need to pre-register drivers.
      driver = await prisma.driver.create({
        data: {
          // UUID is auto-generated by the database default
          ref_id: 'DRV-' + Math.floor(1000 + Math.random() * 9000).toString(),
          phone_primary: phone,
          first_name: 'New',
          last_name: 'Driver',
          license_number: 'PENDING',
          license_expiry: new Date(Date.now() + 31536000000) // 1 year from now
        }
      });
    }

    // Generate JWT
    const jwtPayload = {
      id: driver.id,
      phone: driver.phone_primary,
      role: 'driver'
    };

    const token = jwt.sign(jwtPayload, process.env.JWT_SECRET as string, { expiresIn: '7d' });

    res.json({
      success: true,
      data: {
        token: token,
        expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        user: {
          id: driver.id,
          first_name: driver.first_name,
          last_name: driver.last_name,
          phone: driver.phone_primary,
          role: 'driver',
          driver_id: driver.id
        }
      }
    });
  } catch (error) {
    console.error('Error verifying OTP:', error);
    res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Internal server error' } });
  }
};
