-- AlterTable
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "billing_amount" DECIMAL(12,2);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "paid_amount" DECIMAL(12,2) NOT NULL DEFAULT 0.0;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "balance_due" DECIMAL(12,2);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "carrier_name" TEXT;
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "is_post_trip_settled" BOOLEAN NOT NULL DEFAULT false;
